//import "./tipos/variaveis"
//import'./tipos/array'
//import'./tipos/enums'
//import'./tipos/enums_const'
//import'./tipos/enums_tipos'
//import'./tipos/funcoes'
// import'./tipos/funcoes_tipos'
//import'./tipos/objetos'
//import'./tipos/desafio/produto'
//import'./tipos/uniao'
// import'./tipos/never'
// import'./tipos/null'
// import'./tipos/desafio/desafio_final'
//import'./oo/classe_1'
import'./oo/classe_2'